### ISSUE TITLE
I cannot create a profile

### ISSUE THREAD

**Issue by stech11845** [mrsauravsahu/vscode-manager#57]
Issue Type: <b>Bug</b>

1. Go to Custom Profiles Explorer
2. Click on Add Profile
3. Triggered
Actual result: Profile does not create
Expected result: Profile does create

Extension version: 2.2.0
VS Code version: Code - Insiders 1.69.0-insider (2932e29645f12f08235b7560b3f7d763b8a1cf25, 2022-07-04T10:51:04.591Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by mrsauravsahu** [comment]
Hey I haven't checked this in a while. And I think the newest versions of VSCode are creating issues for profiles. Let me check this out.

**Comment by mrsauravsahu** [comment]
Gave this a try and I'm not able to reproduce the error. Creating profile and launching them works fine. One thing you can try is checking the permission on `C:\Users\<your-user>\.config folder\vscode-manager`. This is where the profiles are created.  If it's not there, you can try creating this folder. 

I'll try to delete my config folder and check again.

**Comment by softorangetech11** [comment]
OK. It was because the `vscode-manager` folder wasn't created. I'll test this out and give you the results.
